### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by yeshacker** [amiel/typingIntent#1]
The name of the function mentioned in the example, in the README file is typingIntent, whereas inside the .js file it's 'typing_intent'. Causes a little confusion. Please fix this.

**Comment by amiel** [comment]
Oh, good point.

**Comment by amiel** [comment]
Ok, I've made the change. Since I'm not using this anymore, I wasn't able to test it. I'd happily merge a pull-request if there's anything I missed.
